### ISSUE TITLE
EKF problem with Az bias estimate

### ISSUE THREAD

**Issue by superjax** [byu-magicc/roscopter#1]
If Az is left unfixed, then it climbs until it gets to about 10 m/s^2.  Or, just enough to cancel out gravity.  Not really sure why.  I fixed it, and I get good enough performance for now.  I'm moving on to velocity control.

**Comment by superjax** [comment]
I would suspect that @nonrevlb may have fixed this in his solution to #8.

**Comment by superjax** [comment]
@nonrevlb,  can you confirm that this issue is solved?

**Comment by jerelbn** [comment]
ekf remove, now using mekf
