### ISSUE TITLE
GPS ground_speed and ground_course don't work

### ISSUE THREAD

**Issue by nonrevlb** [byu-magicc/roscopter#10]
The GPS update that we have working isn't using the ground_speed and ground_course.  I was thinking that it would be good to incorporate this if possible.  We originally turned them off because the chi_error added to ground_course was absurdly huge.  I reported the exact value of chi with no error instead but it still causes bad estimates.  

I believe there may be a problem with the dynamics we came up with.  We had:

```
vg = sqrt(u^2 + v^2)
chi = atan2(v/u)
```

Since chi is measured in a global frame and v and u are in the robot frame, wouldn't this be wrong?  Would it be better to use:
`chi = atan2(pe_dot/pn_dot)`
where pe_dot and pn_dot are from equation 3 of the PDF?

**Comment by superjax** [comment]
Yes.   You're right.  We don't have a great estimate of what `pe_dot` and `pn_dot` are, since we don't have a magnetometer to map `u` and `v` into their respective inertial frame components.  I think that before we do this, we will probably need to first implement a magnetometer in the EKF.

**Comment by jerelbn** [comment]
ekf removed, now using mekf
