### ISSUE TITLE
EKF node - Parameter about frame of Mocap

### ISSUE THREAD

**Issue by superjax** [byu-magicc/roscopter#11]
Depending on the truth source, the frame changes.  The motion capture room published in NWU, while the gazebo simulator publishes in NED.

We can either switch mocap, so that everything we do is in NWU, (I think that is actually a good idea, so we can compare apples to apples when we plot them side-by-side).  Or, we can add a parameter to the ekf node to determine which frame the truth data is coming in on, so we filter accordingly.

**Comment by jerelbn** [comment]
ekf removed, now using mekf
