### ISSUE TITLE
Takes off like stupid sometimes in waypoints

### ISSUE THREAD

**Issue by superjax** [byu-magicc/roscopter#13]
Sometimes, the position controller sends the drone upwards at full throttle.

Reported by @el3ment in NNOA project.

**Comment by superjax** [comment]
Investigating this issue, We just need to saturate the desired acceleration in z to minus gravity.  [Line 243](https://github.com/byu-magicc/ros_copter/blob/2b1f0d76c483793f022d71dff0d6570bc0f668b2/src/controller/controller.cpp#L243)

Otherwise, large negative desired accelerations will contribute to the total desired thrust, and cause an inverted feedback loop.

**Comment by el3ment** [comment]
Will that just make us go upwards at -gravity instead of full throttle?

Robert

**Comment by superjax** [comment]
No.  Because I add gravity back in, if we saturate to gravity, then the commanded thrust will be zero.  We only need to saturate on downward accelerations, because we often have a thrust to weight ratio greater than 2 with multi rotors.

**Comment by el3ment** [comment]
gotcha!
