### ISSUE TITLE
Having a problem building the package

### ISSUE THREAD

**Issue by memphis242** [byu-magicc/roscopter#35]
I am still new to ROS and not sure how the configuration of builds works but I get the following error when running catkin_make from ~/catkin_ws:

![roscopter cmake_build error](https://user-images.githubusercontent.com/25826895/47610287-06eb7f80-da17-11e8-823f-d746d1ef063d.png)

> Project 'roscopter' tried to find library 'rosflight_utils'.  The library
>   is neither a target nor built/installed properly.  Did you compile project
>   'rosflight_utils'? Did you find_package() it before the subdirectory
>   containing its code is included?

I installed all rosflight packages from the Ubuntu repos using sudo apt-get install ros-kinetic-rosflight-pkgs. When I run sudo apt-get install ros-kinetic-rosflight-utils it says it is up to date. Not sure what else to try here.

**Comment by memphis242** [comment]
Wow that was a quick solve. I just cloned the rosflight repo into catkin_ws/src and it worked. #noobThings

**Comment by superjax** [comment]
Hey, thanks for the reminder.  Totally our fault actually - `rosflight_utils` is not installed by the repo version because of some mistakes in the CMake
